### ISSUE TITLE
Unable to Push Images to Index (Authentication Issue)

### ISSUE THREAD

**Issue by ekristen** [ekristen/docker-index#15]
Received email indicating problem with not being able to push images. Have been unable to reproduce.

**Comment by x1022as** [comment]
Here is the situation:
1. git clone the docker-index project
2. 'sudo fig up' in docker-index directory
Containers are up , 'docker login index.private.io' succeeded. And 'docker push index.private.io/test/xxx' failed, here is the error message:
      "FATA[0000] HTTP code 401 while uploading metadata: {"error": "Requires authorization"}"

If set DISABLE_TOKEN_AUTH=true in fig.yml and do some modification in registry(This modification is done according to the error message, and has nothing to do with index), everything is ok, we can pull and push successfully.

**Comment by ekristen** [comment]
`DISABLE_TOKEN_AUTH=true` disables the registry from using authentication of any kind, that is why it works. 

I will try cloning and setting up from scratch as you've outlined on a fresh system tonight, but so far I cannot duplicate and everything works as expected. I will follow up after I've run my test.
