### ISSUE TITLE
Abstract data storage

### ISSUE THREAD

**Issue by ekristen** [ekristen/docker-index#19]
Current Data Access Methods
  * get
  * put
  * delete
  * expire

Storage Primitives
 * users - singular user objects with basic information like name, email, admin flag, namespace permissions
 * tokens - access tokens granted for various layer access during the docker pull and push process
 * repositories - update and track list of current layers, tags for the repository

To Think About
 * Essentially only the `get`, `put`, `delete`, `expire` methods need to be different depending on data storage method.
 * Should the `docker-index` come with multiple storage methods, or should it be roll your own. Example, after abstraction require modules like mongo, any-db, to be separate npm-modules that are just attached to the creation of the docker-index server.

ToDos
 * [ ] redo how webhooks are found, stored, deleted if createReadStream is not available (ie non leveldb)

**Comment by Caligatio** [comment]
Let me start this by saying I'm completely willing/wanting to code up whatever is decided here.

Basically, the storage primitives required in this app seem really straight forward: basically user management.  I propose enumerating all the functionality required for user management and then allowing pluggable persistence backends to implement that however its needed.  To start, I'm thinking:
* Redis (done)
* LeveDB (done, I think)
* any-db (again, not forcing people to use it but make it an option)
* Some sort of MongoDB

Expires-type functionality can be implemented internally using timestamps.  The returned object from the persistence backends can match what the app expects today so all the internals should work.

**Comment by ekristen** [comment]
Awesome sounds like we are on the same page. :)

Question -- do you yourself plan to use any-db? If so I'm curious to understand why an RDMS over redis/level? This is more of my own internal understanding :)

**Comment by ekristen** [comment]
I replaced Redis with LevelDB in `develop` but realistically they are completely interchangeable with the way the current app is coded. Honestly it would be far easier at this point to require additional datastores to just expose `get`, `put`, `delete`, `expire`, `key` and a few others, but that doesn't mean it is necessarily the best way either.

The app still needs to be refactored a little bit to allow the passing in of a custom data store. 

I'm also not sure I want to have "redis" and "level" and "mongo" and "any-db" and "X" all as dependencies in this project, but haven't made a decision on that yet. I think we can work on how to abstract the data store a bit first and then see what makes sense.

**Comment by Caligatio** [comment]
So the big advantage for a RDBMS in a situation like this is it allows easy querying for both user permissions and what permissions exist on a repository/namespace.  If I'm reading things correctly, you would have to parse every single user to find out who has write/read/admin access to a certain namespace (I'm thinking of website showing namespace/project metadata).  If you have 1000 users, that means you have to pull all 1000 users's profiles to compile an answer to the question to "who did I give access to?"  You could keep a namespace permission list too but that means keeping two duplicative datasets in sync.

**Comment by ekristen** [comment]
> So the big advantage for a RDBMS in a situation like this is it allows easy querying for both user permissions and what permissions exist on a repository/namespace.

I couldn't disagree with you more. However in the current state it isn't setup for secondary queries, but that could be changed very easily.

> If I'm reading things correctly, you would have to parse every single user to find out who has write/read/admin access to a certain namespace (I'm thinking of website showing namespace/project metadata). If you have 1000 users, that means you have to pull all 1000 users's profiles to compile an answer to the question to "who did I give access to?" 

You are correct, however this could easily be changed and a secondary index could be created in the key/value store to allow you to simply just grab "namespace:x:users" or whatever and get a list.

> You could keep a namespace permission list too but that means keeping two duplicative datasets in sync.

Depends on how you do it.

@Caligatio so I think before we get too deep in the weeds on rewriting the data storage to abstract it all, lets figure out what exactly you would like to be able to query, and go from there. We can easily add additional admin api calls to get at this information. 

Another question, it sounds like you are wanting to be able to query the database directly?

**Comment by ekristen** [comment]
I updated my last comment FYI with some additional info.

**Comment by Caligatio** [comment]
I really don't understand your resistance to SQL databases.  It's simply 3 tables: a users table, a namespace table, and a many-to-many table for permissions.  You could even go to an image-by-image basis if that is desired (which would require another table).

docker-registry uses a RDBMS as it's backend so there is already an indirect dependency.  If I have to admin a SQL database for the registry, why not just have support for your storage to go in the same space?

Regarding your edit, I'm a bit torn whether for a GUI to use APIs or hit the DB directly.  There are pros and cons to both.

**Comment by ekristen** [comment]
FWIW, I am working on a branch already locally for abstracting the datastore. I should have have a branch to check out in the next couple of days.

As for the rest of this, I enjoy having a conversation. I'm not being difficult to be difficult. 

> I really don't understand your resistance to SQL databases. It's simply 3 tables: a users table, a namespace table, and a many-to-many table for permissions. You could even go to an image-by-image basis if that is desired (which would require another table).

I think that SQL databases are useful for certain things and for others they introduce a lot of overhead for little gain. For such a simple setup, why all the extra overhead of having to do multiple JOIN queries to get the info? 

I'm fairly confident your comment about `docker-registry` using a RDMS is incorrect. You can use SQL for a search backend, but that would be it. The registry doesn't actually store any metadata.

The `docker-index` is the database for the `docker-registry`. The index is responsible for storing the list of layers for each image/repository and their associated tags so that you can pull and push.

Although I would mention that if the reason for SQL is so that it is just "easier" to query for information, that either it might be more beneficial to just add some additional API endpoints to provide the information you seek.

**Comment by ekristen** [comment]
There would need to be more than 3 tables too. 
* users
* tokens
* namespaces
* users to namespaces (and their corresponding permissions)
* webhooks

`namespaces` would either need to contain a column that supports JSON for all the layer information, or the layer information would have to be broken up into individual rows and then reassembled. 

All the API information both post and gets are all JSON data, so being able to store that directly is very valuable instead of having to parse, store in separate rows and then query and reassemble.

**Comment by Caligatio** [comment]
Bah, it looks like the sqlalchemy option is just that, an option.  The docs say "he Docker Registry can optionally index repository information in a database for the GET /v1/search" and links off to the Hub API which has no mention of the search.

So I think the unavoidable issue with using LevelDB is there can be only one process can have the DB open at a time.  This means you cannot have multiple Node.js processes spun up to handle load and you certainly cannot spin up multiple machines to scale up.  If every web page call requires hitting the backend and every push/pull requires hitting the backend, I could see the need for more than a single thread.

This does not apply to Redis but I get the willies any time persistent/critical storage is resident in RAM.

**Comment by ekristen** [comment]
> Bah, it looks like the sqlalchemy option is just that, an option.  The docs say "he Docker Registry can optionally index repository information in a database for the GET /v1/search" and links off to the Hub API which has no mention of the search.

No Worries

> So I think the unavoidable issue with using LevelDB is there can be only one process can have the DB open at a time.  This means you cannot have multiple Node.js processes spun up to handle load and you certainly cannot spin up multiple machines to scale up. If every web page call requires hitting the backend and every push/pull requires hitting the backend, I could see the need for more than a single thread.

You are correct in that only a single process can have the LevelDB instance open at any one time, but there are solutions for that as well, but I won't get into them just yet.

Node is very I/O friendly, having a single instance handling hundreds of connections should be more than sufficient, but I respect the need to run multiple instances. I have never needed multiple instances, therefore I haven't built in support.

Are you going to need to run multiple instances? Might I have an idea as to the size of your organization. I'm sure we can come up with a solution, even if it means building in some extra support into the project.

> This does not apply to Redis but I get the willies any time persistent/critical storage is resident in RAM.

Well Redis has the ability to flush to disk, so you can immediately persist everything to disk, it is just a configuration option.

In terms of moving forward. I'm cleaning up my code a bit and restructuring things as well as playing around with what it would take to abstract things out a bit on the data store side still. I'll push those changes once I have it restructure and the tests are working, I'm about 70% done already with that.

**Comment by ekristen** [comment]
I've taken the first steps in abstracting the data store, I had to reorganize the application so that docker-index could be installable via npm, that way people can pass in a datastore when creating the server. 

https://github.com/ekristen/docker-index/tree/restructure

This doesn't provide support for another datastore method just yet, but it is the step in the right direction.

**Comment by ekristen** [comment]
I'll have to re-think how to do all the webhooks if I am not doing leveldb, (ie the abstraction) I rely on some read stream capabilities of leveldb to ensure all webhooks are found and called and/or removed. I'm going to keep the top entry on this issue up to date with things I find.

**Comment by Caligatio** [comment]
You may have already known about this but apparently Mongo has native support for expire-type operations: http://docs.mongodb.org/manual/tutorial/expire-data/

**Comment by ekristen** [comment]
Thanks. I've decided I will not be abstracting the data storage for this version. Too much work and not enough gain. 

I'm having to write an entirely new index type project for the v2 of the registry, in this new auth service I'm writing I'll be setting it up for additional data sources.

Erik

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
