### ISSUE TITLE
Implement Search?

### ISSUE THREAD

**Issue by ekristen** [ekristen/docker-index#26]
The Docker Hub API spec calls for a `/v1/search` endpoint on the index.

**Comment by rikkuness** [comment]
Is this spec against the index? The registry code has search implemented using SQLalchemy as a backend.

**Comment by ekristen** [comment]
@rikkuness unsure. I just threw the issue up for me to follow up on it sometime. Once upon a time the index spec called for it, but it could have just been a proxy through to the registry or it might have changed entirely.

**Comment by rikkuness** [comment]
There's some definition in the docker-registry readme.md https://github.com/docker/docker-registry#search-engine-options I've managed searching via that API in the past without any real issues.

**Comment by rikkuness** [comment]
Interestingly, now I've got push working I've noticed that the registry doesn't seem to index search data. 

Configured on the registry `SEARCH_BACKEND:sqlalchemy` and `SQLALCHEMY_INDEX_DATABASE:sqlite:////data//search-index.db` the sqlite file is created but it would appear nothing gets appended on a push. All queries to /v1/search on the registry return 0 results.

**Comment by ekristen** [comment]
Search is in fact an index feature but I've never implemented it.

**Comment by rikkuness** [comment]
Will implementing search require another backend datastore that allows retrieving multiple records or does your datastore abstraction (https://github.com/ekristen/docker-index/issues/19) need to allow for this capability?

**Comment by ekristen** [comment]
I'm not sure I'll be implementing search, once I revert things back to 1.4.x I might take a look but all my focus is on v2 right now. Docker's v2 registry will not longer need the index and the they are building a search system too for v2.

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
