### ISSUE TITLE
Add API endpoint to update user password.

### ISSUE THREAD

**Issue by rikkuness** [ekristen/docker-index#27]
Not sure if this is part of the base Docker Index spec but a call to update the user password would be great.

**Comment by ekristen** [comment]
@rikkuness That is not a bad idea. Unfortunately the user would also need the `docker-index-cli` tool to be able to use it at this point.

**Comment by ekristen** [comment]
Actually the `/v1/users/` endpoint which is already implemented has the ability to update a password, there just isn't a build in way via the docker command line utility that I know about to use it, so it'll have to be a curl command or a sub-command that I implement on `docker-index-cli`

**Comment by rikkuness** [comment]
Appreciate that would be part of the CLI tooling yeah, or if someone were to front this index with their own UI using the API calls provided. Another thing I came across was the lack of a call to delete a user account, again this isn't something that the 'real' index would provide in the spec but may be something someone running their own index would need. Appreciate there's already a disable user call though.

**Comment by ekristen** [comment]
@rikkuness so I take it that you are using the index? If so what are you experiences? Feel free to email me.

Adding a delete user function is easy enough, I'll add an issue for it.

**Comment by ekristen** [comment]
https://github.com/ekristen/docker-index/issues/28

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
