### ISSUE TITLE
Login returns 201 for already existing users

### ISSUE THREAD

**Issue by rikkuness** [ekristen/docker-index#32]
When logging on as a user account that already exists in the registry the response is 201, this doesn't break anything but does cause the message `Account created.` to be shown in the docker client even if the account already existed, looking at the standalone registry code I believe the 201 should be returned for new accounts and 200 for existing accounts logging in.

**Comment by ekristen** [comment]
Yes this is indeed a bug. However it is a display bug not a functional one, meaning it has no impact on usability.

**Comment by rikkuness** [comment]
Agreed, functionality is not impacted at all.

**Comment by ekristen** [comment]
Version 2 of the registry is coming out soon. I'm going to fix as many bugs as I can on this project and then this project is probably not going to be touched in regards to features. All work will be done on version 2.

**Comment by rikkuness** [comment]
I don't believe this bug is actually present in 1.4.0, since I switched I've not seen any 201's for existing accounts.

**Comment by ekristen** [comment]
I was referring to the missing headers. In 1.4 the 200 vs 201 should be fixed.
