### ISSUE TITLE
readwrite permission does not appear to allow writing

### ISSUE THREAD

**Issue by Caligatio** [ekristen/docker-index#34]
I started using the Index in earnest a few days ago and ran into the issue of the "readwrite" permission for a user doesn't actually allow them to push the the namespace.  Changing their permission to "admin" or "write" allowed pushing and the "write" permission also allowed reading.

**Comment by ekristen** [comment]
I believe I deprecated the readwrite to sort of follow the github approach of 'admin', 'write', 'read' ... this sounds like a documentation problem on my side. I apologize.

**Comment by Caligatio** [comment]
Ahh ok, I thought I was losing my mind.  I was looking at [middleware](https://github.com/ekristen/docker-index/blob/master/index/middleware.js#L76) and it looks like it's still in the codebase too.
