### ISSUE TITLE
Add support for public and "protected" namespaces

### ISSUE THREAD

**Issue by Caligatio** [ekristen/docker-index#35]
It would be great to allow for entire namespaces to be public (don't even have to be logged in) as well as for an option to just require a user to be logged in (don't need to enumerate each user to be allowed access).

**Comment by rikkuness** [comment]
Any ideas how the public registry handles this? That has the ability to pull images without auth and also secured ones presumably under the same index?

**Comment by ekristen** [comment]
Sure, basically they just have everything set to open. The private registry was designed for private restricted access, never crossed my mind to support open and unauthenticated system.

I'm writing version 2 right now for registry version 2, I can take that into account for this.

**Comment by Caligatio** [comment]
I don't know if it's helpful but there is a decent authorization framework for express/node out there called [MustBe](https://github.com/derickbailey/mustbe).  It may be more work than it's worth to use it instead of your homegrown solution.

**Comment by ekristen** [comment]
It's not super complicated to allow this type of behavior. It just wasn't on my todo list when I originally created it, I figured if someone was using the private registry and not the public everyone should need an account.

I'm taking this into consideration for support in v2 I may back port into 1.x

Erik

Erik

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
