### ISSUE TITLE
Allow admin delegation to users other than "admin"

### ISSUE THREAD

**Issue by Caligatio** [ekristen/docker-index#36]
It appears that there is not a way to give non-repo specific admin rights (i.e. to allow creation of accounts) to other users.  The [unittests](https://github.com/ekristen/docker-index/blob/master/test/test.internal_users.js#L23) create an account with such a capability but I don't see how to do that normally.

**Comment by ekristen** [comment]
What version are you using?

**Comment by Caligatio** [comment]
v1.4.0-RC2

**Comment by ekristen** [comment]
Somehow I missed that. Not sure how. I'll have to push an update, I'll try and do that later today.
