### ISSUE TITLE
Add the ability to manually provision users even if "disable_account_registration" is set

### ISSUE THREAD

**Issue by Caligatio** [ekristen/docker-index#37]
Currently there is no way to enforce any sort of rule that if an account is made that they're actually the person that they claim to be (e.g. I could create an account "ekristen" despite the fact I'm not ekristen).  If there is an external service that can validate users, I'd like the ability for that service to provision them account with the password they choose.

Basically, I'd like it if only admin users can make accounts for others.  Right now, "disable_account_registration" is the closest thing to disabling random account creation but that also kills ALL account creation.

**Comment by ekristen** [comment]
There used to be a create user feature in the cli tool but I removed it at one point but I thought I added it back. I'll take a look.

**Comment by rikkuness** [comment]
If there was a create user function in the CLI tool before does that mean there may still be an add user API call present that can be used even once `disable_account_registration` is set to true?

**Comment by ekristen** [comment]
I can get this added back in.

**Comment by ekristen** [comment]
The endpoints already exists, just need to add the command in `docker-index-cli`

**Comment by ekristen** [comment]
This has been fixed in https://github.com/ekristen/docker-index-cli/commit/628d0f2461a7e82b79823a97db91bc40813597e4
