### ISSUE TITLE
Add ability for namespace admins to add permissions for other users on that namespace

### ISSUE THREAD

**Issue by Caligatio** [ekristen/docker-index#38]
If I'm reading the code correctly, someone has to be a global admin to be able to modify any permissions of another user.  My idea is if someone is an admin for a particular namespace, they should be able to grant other users access to that namespace.

An analogy is the ability on Github to allow other people commit access to your repository even though you're not a global Github admin.

**Comment by ekristen** [comment]
This is a pretty involved change. I'll look into it.

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
