### ISSUE TITLE
login registry

### ISSUE THREAD

**Issue by afengisme** [ekristen/docker-index#43]
hi, 
I used redis + docker-index  + docker-registry(0.9.0) + docker-index-nginx(front end)
After all containers created and started up successfully:
> docker ps -a
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS              PORTS                                      NAMES
a48c7e0206e4        registry:0.9.0                    "docker-registry"      2 weeks ago         Up 2 weeks          0.0.0.0:5000->5000/tcp                     docker-registry
9aa812e31a16        docker-index-nginx:latest         "bash /run.sh"         2 weeks ago         Up 2 weeks          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
f8a5d9ef6de6        ekristen/docker-index:1.4.0-rc1   "node app.js"          2 weeks ago         Up 2 weeks          0.0.0.0:5100->5100/tcp                     docker-index
b4641c0d94cc        dockerfile/redis:latest           "redis-server /etc/r   2 weeks ago         Up 2 weeks          6379/tcp                                   index_redis

I tried to login it:  

> docker login http://xxxx.xxx.com
Username: admin
Password:
Email: xxxx
FATA[0011] Error response from daemon:

actually , I did not know the initial admin password. I input some charactors randomly, obviously it was failed.

then , I saw this as below in readme.md of docker-index:
####
Other Information
Initial Admin Account

When you start the docker index application for the first time, a first run text will be displayed to standard out. This text will contain the randomly set password for the default admin account.
#####

but , when I created and started up the docker-index container, I did not find the "text" except the container ID on std out:

> docker run -d --name="docker-index" -p 5100:5100 -e REGISTRIES=xxxx.xxxx.com --link index_redis:redis ekristen/docker-index:1.4.0-rc1
f8a5d9ef6de622f289fdf7ced1e5e2312200a7e5cea39194b1889cf4316abc54

Anyone ever encountered this ? 

thanks a lot for the help in advance.

**Comment by afengisme** [comment]
> docker logs -f <docker-index container ID>
docker-index listening at http://0.0.0.0:5100
upgrade complete
----------------------------------------------------------------------

 First Time Initialization Detected

 Default username and password created

 User: admin
 Pass: f59a0163b9657e2fa73b3378

**Comment by afengisme** [comment]
# docker logs -f 0a1d046db8bf
docker-index listening at http://0.0.0.0:5100
upgrade complete
----------------------------------------------------------------------

 First Time Initialization Detected

 Default username and password created

 User: admin
 Pass: f59a0163b9557e2fa73b3378

**Comment by rikkuness** [comment]
This is expected behavior when starting a container with the -d flag set, if you started in the foreground with -i and -t you would have seen the output.

**Comment by ekristen** [comment]
+1 @rikkuness 

@afengisme looks like you got the info.
