### ISSUE TITLE
using the fig.yml

### ISSUE THREAD

**Issue by reasonerjt** [ekristen/docker-index#44]
Hi, I try to understand how docker-index work via this project and try to run it on my env.
This maybe a stupid question but these values:

INDEX_ENDPOINT=https://index.private.io
REGISTRIES=registry.private.io

These hostnames are mocked right?  If I don't have a dns how can I start the registry and index containers as it seems they depends on each other's hostname?

**Comment by ekristen** [comment]
The `fig.yml` is for development and testing only. If you want to use the index/registry using fig you'll need to use DNS locally on your system to be able to get it to work. It is possible to do it without fig, but you'll have to start the registry and index separately and without HTTPS you have to pass some additional values to the docker client to get it to talk to an insecure index.

You can always run https://github.com/ekristen/dns-proxy locally to get better control over local DNS or use your `/etc/hosts` file.

**Comment by reasonerjt** [comment]
Yep, installed dnsmasq and got things work, thanks
