### ISSUE TITLE
pushing failed after passed login

### ISSUE THREAD

**Issue by afengisme** [ekristen/docker-index#45]
Hi,
After deploy the docker-index-nginx + redis + docker-index + docker-registry by fig:

curl testing:
curl --cacert ca.crt https://admin:d29a7d9665c473eed436c47a@xxx.xxx.com
{"code":"ResourceNotFound","message":"/ does not exist"}

log from docker-index container:
{"code":"ResourceNotFound","message":"/ does not exist"}
{"name":"audit","hostname":"3cc231ec7c24","pid":1,"audit":true,"level":30,"req_id":"4bb63560-ee34-11e4-bddc-4163c283e26d","req":{"method":"GET","url":"/","headers":{"host":"xxx.xxx.com","x-real-ip":"10.0.42.1","connection":"close","authorization":"Basic YWRtaW46ZDI5YTdkOTY2NWM0NzNlZWQ0MzZjNDdh","user-agent":"curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3","accept":"*/*"},"httpVersion":"1.0","trailers":{},"version":"*","timers":{}},"res":{"statusCode":404,"headers":{"content-type":"application/json","content-length":56},"trailer":false},"latency":2,"_audit":true,"msg":"handled: 404","time":"2015-04-29T05:55:10.390Z","v":0}

Login and push testing:
docker login https://xxx.xxx.com
Username: admin
Password:
Email: xxx.xxx@xxx.com
Login Succeeded

docker tag 4fb2d29a290b xxx.xxx.com/test_image

docker push xxx.xxx.com/test_image
The push refers to a repository [xxx.xxx.com/test_image] (len: 1)
Sending image list
FATA[0000] Error: Status 403 trying to push repository test_image: "access denied"

logs from docker-index container:
{"name":"audit","hostname":"3cc231ec7c24","pid":1,"audit":true,"level":30,"req_id":"03210310-ee35-11e4-bddc-4163c283e26d","req":{"method":"GET","url":"/v1/_ping","headers":{"host":"xxx.xxx.com","x-real-ip":"10.0.42.1","connection":"close","user-agent":"Go 1.1 package http","accept-encoding":"gzip"},"httpVersion":"1.0","trailers":{},"version":"*","timers":{"parseAccept":275,"parseQueryString":261,"readBody":53,"parseBody":31,"handler-4":755}},"res":{"statusCode":200,"headers":{"x-docker-registry-version":"0.8.0"},"trailer":false},"latency":2,"_audit":true,"msg":"handled: 200","time":"2015-04-29T06:00:18.113Z","v":0}
{"name":"audit","hostname":"3cc231ec7c24","pid":1,"audit":true,"level":30,"req_id":"0323c230-ee35-11e4-bddc-4163c283e26d","req":{"method":"GET","url":"/v1/_ping","headers":{"host":"xxx.xxx.com","x-real-ip":"10.0.42.1","connection":"close","user-agent":"Go 1.1 package http","accept-encoding":"gzip"},"httpVersion":"1.0","trailers":{},"version":"*","timers":{"parseAccept":121,"parseQueryString":99,"readBody":27,"parseBody":8,"handler-4":488}},"res":{"statusCode":200,"headers":{"x-docker-registry-version":"0.8.0"},"trailer":false},"latency":1,"_audit":true,"msg":"handled: 200","time":"2015-04-29T06:00:18.131Z","v":0}
{"name":"docker-index","hostname":"3cc231ec7c24","pid":1,"level":20,"headers":{"host":"xxx.xxx.com","x-real-ip":"10.0.42.1","connection":"close","content-length":"1792","user-agent":"docker/1.4.0 go/go1.3.3 git-commit/4595d4f kernel/3.8.0-29-generic os/linux arch/amd64","authorization":"Basic Og==","content-type":"application/json","x-docker-token":"true","accept-encoding":"gzip"},"url":"/v1/repositories/docker-index-nginx/","msg":"","time":"2015-04-29T06:00:18.174Z","v":0}
{"name":"docker-index","hostname":"3cc231ec7c24","pid":1,"level":20,"user":"","statusCode":403,"message":"access denied: user not found","msg":"","time":"2015-04-29T06:00:18.177Z","v":0}

thanks a lot.

**Comment by ekristen** [comment]
Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
