### ISSUE TITLE
Will you focus on registry 2.0?

### ISSUE THREAD

**Issue by xianlubird** [ekristen/docker-index#46]
I want to add search function to this repo, will you agree?

**Comment by ekristen** [comment]
I have a alpha version of registry 2.0 implemented already, but it isn't ready. Unfortunately registry 2.0 doesn't support search yet, that is something docker is still working on.

**Comment by xianlubird** [comment]
I did not find the registry 2.0 index alpha repo.Can you show me ? I want to learn it and support it if I can.

**Comment by xianlubird** [comment]
Ok, Thank you very much.

**Comment by ekristen** [comment]
Version 2 coming soon.

Docker registry v1 is about to be deprecated entirely from the docker engine, this project will soon be deprecated as well.
